### ISSUE TITLE
animated tiles + some other features

### ISSUE THREAD

**Issue by blurymind** [notnullgames/tiled-kaboom#1]
The demo page indicates that animated tiles aren't supported.

Are they a planned feature?

Other features I wonder if supported:
- tilemap layer opacity
- tilemaps sharing a tileset
- automatic generation of collisions from tiled data
- other metadata from tiled,which can be read to trigger events on collision

**Comment by konsumer** [comment]
I have my current plans in [the todo](https://github.com/notnullgames/tiled-kaboom#todo). With most of these, this lib is just a translator from TIled's map format to kaboom, and then you are free to use that directly in kaboom code, as you normally would do that thing.

- "tilemaps sharing a tileset" is a more near-in goal for me, as it can really cut down on map sizes (especially when coupled with compression of layer-maps.) A primary goal is making maps size-efficient enough to use directly on the web (so they don't need to be exported to another format.) It lends itself to a more open source-first sort of approach, and also a single-source-of-truth, which I really like.
- "tilemap layer opacity"  - I'm not sure how to do layer-opacity in kaboom, as I didn't see it in the docs or any tutorials I came across. This would be a great subject to explore, but for now, you can hide layer (so opacity of 1 or 0.)
- on "automatic generation of collisions from tiled data", it currently does what kaboom does (it's a regular kaboom textual tilemap) but I'd also like to use Tiled's physics-shape-editing, eventually, too, for more fine-grained shapes (for example the combo of using tiled terrain-brushes with the edge of the coast built-in as physics shape is pretty awesome.)
- "other metadata from tiled" yeh, this is the "custom properties" stuff in TODO. It's fairly simple to grab it from the JSON, directly, but it might be cool to add more with this. I am torn on features like this, as I think doing what you want with kaboom directly is good (liek it's all inJSON, so just pull out what you need and do what you want) but maybe a simple translator function like `getProperties(mapCoords, layerName)` would be helpful to get the current properties for a layer.

I happily accept PRs, if you want to work on any of this. Make a discussion issue first, so we can talk about it, and make sure it's something we agree on a need for, then go for it! The overall goal for me is to stay simple, not get too in the way of kaboom & tiled's awesomeness, so I chose to not wrap them too much, just provide the tools to load a tiled map and do what you want with it, in kaboom. I'm open to a more complete ready-made solution to "load a tiled map into kaboom" but first I'm more interested in supporting the basic features of each (like external tilesets, physics-editor and animations would be sick.)

I wonder if some of these could be separate kaboom plugins. Like maybe you load the tiled-map part with this, and hand the map-object (with all the tiles loaded) to a separate physics plugin. This lib does a pretty good job of turning a tiled-map into something that is readable (unbase64/uncompress/turn into kaboom text-map/etc) so maybe it could be up to other plugins to implement the other stuff.

**Comment by konsumer** [comment]
Since kaboom itself doesn't seem to directly have support for animations directly in tilemap, it might be another thing that `loadTiledMap` returns. like if you have info about what layer it's on, and the sprite-frames it uses, you could add them in after the `addLevel` yourself. I could see returning a collection of object-shapes that defines the areas that you can loop over with `area/solid`, but I don't see anything for complex shapes (like a squigly coastline) it all seems per-rectangle. with that in mind, maybe just a property for all tiles that are solid, like `solid=true` would make sense, but it's basically up to however you want to do that. One thing that might be useful is to return the "port-parsed" copy of the map, that is after it's been decompressed/turned into a n array of tile-ids, etc. Armed with that, it would be enough to work out other things in your own kaboom code, without having to duplicate all that stuff.

**Comment by konsumer** [comment]
I added returning the decompressed/parsed map-object (`mapObj`.)

It's published in tiled-kaboom@0.0.11 (on npm) and should show up everywhere else, soon.

So for now, you could make your own tile-properties parsing pretty simply, by looping over an object layer, or whtaver else, and pull out the properties.

I also added [some demo code](https://github.com/notnullgames/tiled-kaboom/blob/2b3595eff325a63a35b084c3459b91ed867a23bd/index.html#L54-L67) for looking up object-properties. You can see it's very easy to use, even without any helpers or whatever.

**Comment by konsumer** [comment]
I made a bunch of issues to track the TODOs, so I will close this. Feel free to comment on the individual issues.
